### PR TITLE
initial commit of script to change apostrophe, quotation mark & em dash

### PR DESCRIPTION
**Pull request by rsperberg**
Added ability to run this script from cl with input & output filenames from earlier version tested with Rime of the Ancient Mariner

### CODE REVIEW

**Comment by sethwoodworth** [comment]
Looks good.  Want to add a paragraph description or so in the readme?

**Comment by rsperberg** [comment]
Sure.

Is this the way to handle all subsequent changes to this script — via pull request that you merge?

**Comment by sethwoodworth** [comment]
I should have given you write access to this repo.  Feel free to push
directly to it.  I'd rather have the bleeding edge. If other folks start
relying on it, we can start using branches.

**Comment by rsperberg** [comment]
OK, so this is what I'll do
- make changes to my local fork
- push them to my GitHub origin  (e.g., `git push origin master`)
- then push them to upstream master (e.g., `git push upstream master`)

Right?

**Comment by sethwoodworth** [comment]
Sounds good to me.

**Pull request merged**
