### PR TITLE
add many patterns based on 'Heart of Darkness'

### PR DESCRIPTION
**Pull request by rsperberg**

### CODE REVIEW

**Comment by rsperberg** [comment]
I was at the Strand Bookstore last weekend, where my daughter found a $2 bargain book, "A Conrad Argosy," printed in 1942.

Because Conrad's punctuation is so eccentric by contemporary measures, these texts provide a really strenuous workout for the punctuation-cleanup script. And the printed text lets me resolve any ambiguities that the e-text may have.

So I'll work through the 12 remaining pieces by Conrad to further refine the script.

**Comment by sethwoodworth** [comment]
Feel free to make your changes via PR, but you should also feel free to merge these yourself!

**Comment by eshellman** [comment]
For heart of darkness, are you working with the html or with the plain text? because the plain text uses some markup like 
_papier-mache_
 --
. . .  

The double dash get converted to a unicode emdash in the html

**Comment by sethwoodworth** [comment]
The _Heart_ PRs have been against the .txt file

**Comment by rsperberg** [comment]
@sethwoodworth, I'd like to merge the script changes directly, without requiring you to do it, but I'm unclear on how to do that. As I wrote, I tried to push the changes upstream from my local copy but that didn't work. 

What should I be doing?

**Comment by rsperberg** [comment]
@eshellman, I've been working solely with the ASCII text so far. This script changes only `'`, `"` and `--`.

I know that underscores used to indicate italic get converted when html markup is added and I see that two consecutive hyphens get converted to an mdash entity. (There are 20 or 21 instances in _Heart of Darkness_ where they should be 2-em dashes in length.) If Unicode characters are used for quotes and apostrophes in the plain-text, I don't see any reason not to use the Unicode dash as well. It's not a question of markup, as `<h1>` and `<i>` and `<p>` are and which remain excluded from the `.txt`.

Btw, I'm awfully suspicious of the text used to produce this version. Looking at Google Books, there are a multitude of editions and only one italicizes this word. I think also there may be punctuation that precedes an em dash that Conrad-era editions included but this one drops (not something I checked).

**Comment by sethwoodworth** [comment]
You should be able to do:

```
git remote add gh git@github.com:gitenberg-dev/scripts.git
git pull gh master  # might not be needed, you might have to get the merge commits from this repo
git push gh master
```

**Comment by sethwoodworth** [comment]
Re: edition.  The low `book_id` number (216) suggests this book was an early PG release.

From the `old/` [folder](https://github.com/GITenberg/Heart-of-Darkness_219/blob/master/old/hdark10.txt#L33-L36)

> The equipment: an IBM-compatible 486/50, a Hewlett-Packard
> ScanJet IIc flatbed scanner, and Calera Recognition Systems'
> M/600 Series Professional OCR software and RISC accelerator board
> donated by Calera Recognition Systems.

So probably quite old.  I believe PG and Distributed Proofreaders have gotten a lot better about punctuation over time.  I can't find any old scans on OpenLibrary to confirm either way.

Keep going!

**Comment by rsperberg** [comment]
I added `gh git@github.com:gitenberg-dev/scripts.git` as a remote, but attempting to push changes to the script yielded this error message:

```
ERROR: Permission to gitenberg-dev/scripts.git denied to rsperberg.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by sethwoodworth** [comment]
My bad! I added you to the organization but not the repo.  You should be able to push/pull now.

**Comment by rsperberg** [comment]
OK.

Have successfully pushed most recent changes to repo. I note that some lines have inaccurate comments, so this is something I need to correct.

Also the patterns need to be refactored. Perhaps changes specific to a file (or author, Conrad being a perfect example for the way he represents dialect) should be placed in a separate file that's then `require`d in the main `punctuation-cleanup.js` script.

**Comment by sethwoodworth** [comment]
Lets go ahead and rename this repo punctuation-cleanup.  We're going to have enough complexity here that it makes sense to release this as a npm module IMO.

**Comment by eshellman** [comment]
A thought: this punctuation clean-up has the characteristic that the reverse transformation is trivial. so a method cleanDown would be much shorter than cleanUp.

Here's where I'm going with this. We are likely to adopt a new "source" format from which other types files can be derived. If the existing gutenberg text format (with conventions such all-quotes-are-straight) is really well defined, then there would be utility in being able to derive it from the new source file.

if cleanUp is an important step in getting text.txt to the new source file, call it text.ascii, then cleanDown would be the corresponding step in text.ascii -> text.txt

The benefit in keeping text.txt around would be:
1. mooting an argument against feeding changes back to PG
2. clearer diffs with PG

**Comment by sethwoodworth** [comment]
I don't think cleanDown is something we need to address.  Converting from Unicode to pure-ascii is something that has very defined algorithms. For instance, in python it is a one-liner.  I'm happy to document unicode > ascii on a wiki page somewhere.

I am leaning towards removing the <book_id>.txt file in favor of the <book_id>.asciidoc file, but lets move this conversation to the mailing list.

**Pull request merged**
